import type { Metadata } from "next";


import "./globals.css";
import { NavbarMenu} from "@/components/header/navBar/nav-bar-main";
import {lexend} from "@/fonts/googleFonts";


export const metadata: Metadata = {
  title: "Cater Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${lexend.className} overflow-x-hidden antialiased`}

      >
      <header className="w-screen sticky top-0 z-40 bg-white">
          <NavbarMenu />
      </header>

        {children}

      </body>
    </html>
  );
}
