import type { Metadata } from "next";


import "./globals.css";
import { NavbarMenu} from "@/components/header/navBar/nav-bar-main";
import {lexend} from "@/fonts/googleFonts";


export const metadata: Metadata = {
  title: "Cater Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light ">
    <head>
        <script
            dangerouslySetInnerHTML={{
                __html: `
              window.addEventListener('load', function() {
                document.documentElement.classList.remove('loading');
              });
            `,
            }}
        />
    </head>
    <body
        className={`${lexend.className} overflow-x-hidden antialiased`}

    >

    <header className="z-10000 w-screen">

        <NavbarMenu/>
    </header>

    {children}

    </body>

    </html>
  );
}
